services:
  api-mysql:
    profiles: ["mysql"]
    restart: unless-stopped
    build:
      context: .
    ports:
      - 8080:8080
    environment:
    - DATABASE_TYPE=mysql
    - DATABASE_DATASOURCE_NAME=root:root@tcp(mysql:3306)/espresso-api?parseTime=true
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/main", "healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    profiles: ["mysql"]
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: espresso-api
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-proot", "-D", "espresso-api", "-e", "SELECT 1"]
      start_period: 20s
      interval: 5s
      timeout: 5s
      retries: 10

  postgres:
    profiles: ["postgres"]
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: espresso-api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d espresso-api"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  api-postgres:
    profiles: ["postgres"]
    restart: unless-stopped
    build:
      context: .
    ports:
      - 8080:8080
    environment:
    - DATABASE_TYPE=postgres
    - DATABASE_DATASOURCE_NAME=postgres://root:root@postgres:5432/espresso-api?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/main", "healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
