version: '3.1'

services:
  api:
    restart: always
    build:
      context: .
    ports:
      - 8080:8080
    environment:
    - DATABASE_TYPE=mysql
    - DATABASE_DATASOURCE_NAME=root:root@tcp(mysql:3306)/espresso-api?parseTime=true
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: espresso-api
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: espresso-api
