apiVersion: v1
kind: Service
metadata:
  name: espresso-api-go
  labels:
    app: espresso-api-go
spec:
  type: ClusterIP
  selector:
    app: espresso-api-go
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080