name: HTTP tests suite for swagger

vars:
  baseuri: http://127.0.0.1:8080

testcases:
- name: GET /swagger.json matches swagger.json
  steps:
  - type: readfile
    path: ../docs/swagger.json
    assertions:
    - result.err ShouldBeEmpty
    - result.content ShouldNotBeEmpty
    vars:
      expectedSwagger:
        from: result.content

  - type: http
    method: GET
    url: "{{ .baseuri }}/swagger.json"
    assertions:
    - result.statuscode ShouldEqual 200
    - result.headers.content-type ShouldEqual "application/json"
    vars:
      actualSwagger:
        from: result.body

  - type: exec
    script: test '{{.actualSwagger | b64enc}}' = '{{.expectedSwagger | b64enc}}'
    assertions:
    - result.code ShouldEqual 0