name: Run e2e tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  e2e:
    strategy:
      matrix:
          testsuites:
            - venom.e2e.roasters.yaml
            - venom.e2e.sheets.yaml
            - venom.e2e.beans.yaml
            - venom.e2e.shots.yaml
            - venom.e2e.swagger.yaml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"
        cache: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install venom
      run: |
        curl https://github.com/ovh/venom/releases/download/v1.1.0/venom.linux-amd64 -L -o /usr/local/bin/venom && chmod +x /usr/local/bin/venom
        venom version

    - name: Docker compose up
      run: docker compose up -d --wait

    - name: Debug when failure happened
      if: ${{ failure() }}
      run: docker compose logs

    - name: Run sql migrations
      run: go run main.go migrate up

    - name: Run e2e tests with venom
      run: |
        export IS_TTY=true
        venom run -vv ./e2e/${{ matrix.testsuites }}